trailingComma: "all"
tabWidth: 4
semi: true
singleQuote: false
printWidth: 80
useTabs: true
bracketSpacing: true
arrowParens: always
overrides:
  - files: "*.json"
    options:
	  tabWidth: 2
      semi: true
	  useTabs: false
