version: '3.7'
services:
  worker:
    build:
      context: .
    networks:
      nt_test:
    command: node src/workers/worker-blocking.js
    # command: node src/workers/worker-subscribe.js
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./example/src:/app/example/src
    environment:
      MONGO_SERVER: mongo-server.local
      REDIS_SERVER: redis-server.local

  app:
    build:
      context: .
    networks:
      nt_test:
    command: node_modules/.bin/nodemon --inspect=0.0.0.0:6000 src/index.js
    # command: node src/index.js
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./example/server.csr:/app/example/server.csr
      - ./example/server.crt:/app/example/server.crt
      - ./example/server.key:/app/example/server.key
      - ./example/src:/app/example/src
      - ./example/package.json:/app/example/package.json
    environment:
      MONGO_SERVER: mongo-server.local
      REDIS_SERVER: redis-server.local

  cache-redis-example:
    build:
      context: ./
      dockerfile: examples.Dockerfile
    command: node src/cache-redis.example.js
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    networks:
      nt_test:
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres-server.local
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db123
      REDIS_HOST: redis-server.local
    depends_on:
      - redis
      - postgres

  redis:
    build:
      context: ./redis
      dockerfile: redis.Dockerfile
    networks:
      nt_test:
        aliases:
          - redis-server.local

  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    networks:
      nt_test:
        aliases:
          - postgres-server.local
  db:
    image: mongo:3.1
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      nt_test:
        aliases:
          - mongo-server.local
networks:
  nt_test:
